FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip setuptools wheel && \
    pip install --no-cache-dir -r requirements.txt

COPY handler_fastapi.py .

EXPOSE 8000

CMD ["python", "-u", "handler_fastapi.py"]
